<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MGroup.LinearAlgebra.Distributed" Version="0.1.0-unstable.224" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="NumSharp" Version="0.30.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MGroup.Solvers\MGroup.Solvers.csproj" />
  </ItemGroup>

</Project>
