<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- Import the global props file for development on local machines-->
  <Import Project="..\..\..\Directory.Build.props" Condition="Exists('..\..\..\Directory.Build.props')" />
  <PropertyGroup>
    <UseLocalMSolveProjects Condition="'$(UseLocalMSolveProjects)' == ''">false</UseLocalMSolveProjects>
  </PropertyGroup>

  <ItemGroup Condition="'$(UseLocalMSolveProjects)' == 'false'">
    <PackageReference Include="MGroup.LinearAlgebra.Distributed" Version="0.1.0-unstable.291" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseLocalMSolveProjects)' == 'true'">
    <ProjectReference Include="..\..\..\LinearAlgebra\src\MGroup.LinearAlgebra.Distributed\MGroup.LinearAlgebra.Distributed.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MGroup.Solvers\MGroup.Solvers.csproj" />
  </ItemGroup>

</Project>
